---
- hosts: all
  gather_facts: no
  become: true
  vars: 
    firstname: sai 
  tasks:
    - name: Create a HTTP Server
      yum:
        name: httpd
        state: latest
    - name: copy index.html
      template:
        src: index.html
        dest: /var/www/html/index.html    
    - name: Start the HTTP Server
      service:
        name: httpd
        state: started
...
